#!/bin/bash
# Compile TAPNext++ per-step ONNX graphs to INT8 BModel on BM1688/BM1684X.
#
# Mirrors gen_fp16bmodel_mlir.sh but inserts a calibration step between
# model_transform and model_deploy:
#   1. model_transform.py    : ONNX -> MLIR (precision-agnostic, same as FP16)
#   2. gen_cali_table_ort.py : MLIR + real-rollout npz samples -> calibration table
#   3. model_deploy.py       : MLIR + table --quantize INT8 -> INT8 bmodel
#
# In addition to the pure-INT8 bmodel, a mixed-precision variant is built:
#   4. gen_mix_qtable.py     : ONNX + MLIR -> qtable (prediction heads in F16)
#   5. model_deploy.py       : MLIR + table + qtable -> INT8-mix bmodel
# The prediction heads (coordinate_head, visible_head) and soft-argmax are kept
# in F16 to prevent the quantization degeneration where pure-INT8 outputs
# collapse to (1.0, 1.0).
#
# Calibration data (../datasets/cali_data/{init,step}_cali.txt) is generated by
# tools/gen_cali_data.py: a PyTorch recurrent rollout dumps per-step inputs as
# .npz keyed by ONNX input name. The 24 cache tensors come from a real rollout
# (not random) so the state-dependent RG-LRU/CausalConv1D layers see realistic
# activations. Frames are random [-1,1] for POC; replace with real preprocessed
# video for production.
#
# The calibration table is generated by tools/gen_cali_table_ort.py via ONNX
# Runtime, NOT by run_calibration.py.  run_calibration's MLIR reference
# interpreter needs >28 GB RAM for this 244M-param model (holds all weights +
# every intermediate without freeing) which OOMs on a 32 GB host.  The ORT
# approach frees intermediates between samples (~3 GB peak) and is run on the
# HOST in the torch 1.13 export venv (not in this container — ORT is not
# installed here).  This script therefore expects the cali tables to already
# exist; generate them first on the host with:
#
#   /tmp/tapnext_export_venv/bin/python ../tools/gen_cali_table_ort.py \
#       --onnx ../models/onnx/tapnext_init.onnx --mlir tapnext_init.mlir \
#       --data-list ../datasets/cali_data/init_cali.txt --input-num 6 \
#       -o tapnext_init_cali_table
#   /tmp/tapnext_export_venv/bin/python ../tools/gen_cali_table_ort.py \
#       --onnx ../models/onnx/tapnext_step.onnx --mlir tapnext_step.mlir \
#       --data-list ../datasets/cali_data/step_cali.txt --input-num 30 \
#       -o tapnext_step_cali_table
#
# All 27 step-graph inputs are plain float32 tensors (no --mean/--scale): the
# frame is already-normalized [-1,1] and the 24 caches + step + query_points are
# state, not images.
model_dir=$(dirname $(readlink -f "$0"))

if [ ! $1 ]; then
    target=bm1684x
    target_dir=BM1684X
else
    target=${1,,}
    target_dir=${target^^}
    if test $target = "bm1684"
    then
        echo "bm1684 do not support int8 with fp16"
        exit
    fi
fi

outdir=../models/$target_dir
cali_dir=../datasets/cali_data

# POC static shapes: 256x256, Q=1.
# 1025 = 32*32 video patches (256/8) + 1 query token.
MODEL_SIZE=256
NUM_TOKENS=$(( (MODEL_SIZE/8)*(MODEL_SIZE/8) + 1 ))  # 1025

# Step-graph input shapes: frame, step, query_points, then 12x(rg_lru, conv1d).
step_shapes="[[1,3,${MODEL_SIZE},${MODEL_SIZE}],[1],[1,1,3]"
for i in $(seq 1 12); do
    step_shapes="${step_shapes},[${NUM_TOKENS},768],[${NUM_TOKENS},3,768]"
done
step_shapes="${step_shapes}]"

function gen_mlir()
{
    # $1 = graph name (init|step), $2 = input_shapes
    model_transform.py \
        --model_name tapnext_$1 \
        --model_def ../models/onnx/tapnext_$1.onnx \
        --input_shapes "$2" \
        --mlir tapnext_$1.mlir
}

function gen_cali_table()
{
    # $1 = graph name (init|step)
    # The calibration table is generated on the HOST by gen_cali_table_ort.py
    # (ONNX Runtime, ~3 GB peak) — see the header comment for the exact commands.
    # run_calibration.py is NOT used: its MLIR reference interpreter needs >28 GB
    # for this 244M-param model and OOMs on a 32 GB host.  This function just
    # verifies the table exists; if missing, print instructions and exit.
    if [ ! -f tapnext_$1_cali_table ]; then
        echo "ERROR: tapnext_$1_cali_table not found."
        echo "Generate it on the host with tools/gen_cali_table_ort.py (see header comment)."
        exit 1
    fi
    echo "[cali] reusing pre-generated tapnext_$1_cali_table ($(wc -l < tapnext_$1_cali_table) entries)"
}

function gen_int8bmodel()
{
    # $1 = graph name (init|step)
    model_deploy.py \
        --mlir tapnext_$1.mlir \
        --quantize INT8 \
        --chip $target \
        --calibration_table tapnext_$1_cali_table \
        --model tapnext_${1}_int8_1b.bmodel

    mv tapnext_${1}_int8_1b.bmodel $outdir/
    if test $target = "bm1688"; then
        model_deploy.py \
            --mlir tapnext_$1.mlir \
            --quantize INT8 \
            --chip $target \
            --calibration_table tapnext_$1_cali_table \
            --model tapnext_${1}_int8_1b_2core.bmodel \
            --num_core 2
        mv tapnext_${1}_int8_1b_2core.bmodel $outdir/
    fi
}

function gen_mix_qtable()
{
    # $1 = graph name (init|step)
    # Identify prediction-head + soft-argmax ops and mark them F16.
    python3 ../tools/gen_mix_qtable.py \
        --onnx ../models/onnx/tapnext_$1.onnx \
        --mlir tapnext_$1.mlir \
        --chip $target \
        -o tapnext_${1}_mix_qtable
}

function gen_mix_int8bmodel()
{
    # $1 = graph name (init|step)
    # INT8 with prediction heads in F16 (via --quantize_table).
    model_deploy.py \
        --mlir tapnext_$1.mlir \
        --quantize INT8 \
        --chip $target \
        --calibration_table tapnext_$1_cali_table \
        --quantize_table tapnext_${1}_mix_qtable \
        --model tapnext_${1}_int8_mix_1b.bmodel

    mv tapnext_${1}_int8_mix_1b.bmodel $outdir/
}

pushd $model_dir
if [ ! -d $outdir ]; then
    mkdir -p $outdir
fi

# init graph: 2 inputs. Calibration table (1402 entries = 2 inputs + 1204 ORT
# intermediates + 196 defaults) is pre-generated on the host from 6 real-rollout
# samples via gen_cali_table_ort.py.
gen_mlir init "[[1,3,${MODEL_SIZE},${MODEL_SIZE}],[1,1,3]]"
gen_cali_table init
gen_int8bmodel init
gen_mix_qtable init
gen_mix_int8bmodel init

# step graph: 27 inputs. Calibration table (1467 entries = 27 inputs + 1256 ORT
# intermediates + 184 defaults) is pre-generated on the host from 30 real-rollout
# samples via gen_cali_table_ort.py.
gen_mlir step "$step_shapes"
gen_cali_table step
gen_int8bmodel step
gen_mix_qtable step
gen_mix_int8bmodel step

popd
